# Generated by Django 4.0.1 on 2022-01-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0002_auto_20220121_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
