# Generated by Django 4.0.1 on 2022-01-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Enter year, make, model of vehicle', max_length=200)),
                ('color', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
