# Generated by Django 4.0.1 on 2022-01-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20220123_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('user_type', models.CharField(choices=[('U', 'User'), ('D', 'Driver')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
