# Generated by Django 4.0.1 on 2022-01-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0018_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_driver', to='ride.user'),
        ),
    ]
