# Generated by Django 4.0.1 on 2022-01-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0020_alter_ride_driver_alter_ride_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['arrival']},
        ),
    ]
