# Generated by Django 4.0.1 on 2022-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0032_auto_20220129_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
