# Generated by Django 4.0.1 on 2022-01-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0033_ride_capacity_alter_ride_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='capacity',
        ),
        migrations.AddField(
            model_name='ride',
            name='capacity_remaining',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
