# Generated by Django 4.0.1 on 2022-01-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0037_auto_20220130_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='rider',
            name='ride',
        ),
        migrations.AddField(
            model_name='rider',
            name='ride',
            field=models.ManyToManyField(to='ride.Ride'),
        ),
        migrations.RemoveField(
            model_name='rider',
            name='rider',
        ),
        migrations.AddField(
            model_name='rider',
            name='rider',
            field=models.ManyToManyField(to='ride.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
