# Generated by Django 2.2.26 on 2022-01-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0039_auto_20220130_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='ride',
        ),
        migrations.AddField(
            model_name='rider',
            name='ride',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='ride.Ride'),
        ),
        migrations.RemoveField(
            model_name='rider',
            name='rider',
        ),
        migrations.AddField(
            model_name='rider',
            name='rider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rider', to='ride.User'),
        ),
    ]
