# Generated by Django 4.0.1 on 2022-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0045_alter_ride_id_alter_rider_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='special_request',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='special_request',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
