# Generated by Django 4.0.1 on 2022-01-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0046_ride_special_request_vehicle_special_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='special_request',
            new_name='special_info',
        ),
    ]
