# Generated by Django 4.0.1 on 2022-01-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0046_auto_20220131_1138'),
        ('ride', '0047_rename_special_request_vehicle_special_info'),
    ]

    operations = [
    ]
