# Generated by Django 4.0.1 on 2022-01-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0048_merge_20220131_1322'),
        ('ride', '0050_auto_20220131_1322'),
    ]

    operations = [
    ]
