# Generated by Django 4.0.1 on 2022-01-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0053_merge_20220131_1436'),
        ('ride', '0054_auto_20220131_1435'),
    ]

    operations = [
    ]
