# Generated by Django 4.0.1 on 2022-01-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0058_alter_ride_id_alter_rider_id_alter_user_id_and_more'),
        ('ride', '0059_auto_20220131_1734'),
    ]

    operations = [
    ]
