# Generated by Django 4.0.1 on 2022-01-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0060_merge_20220131_1817'),
        ('ride', '0061_auto_20220131_1826'),
    ]

    operations = [
    ]
