# Generated by Django 4.0.1 on 2022-01-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0063_ride_license_plate_alter_ride_id_alter_rider_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='license_plate',
            field=models.CharField(blank=True, default=None, max_length=7),
        ),
    ]
