# Generated by Django 4.0.1 on 2022-01-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0064_alter_ride_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='license_plate',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
